---
# tasks file for frontend
- name: Create dest folder
  file:
    path: /var/www/collect/html
    state: directory

- name: Copy site content
  synchronize:
    src: files/collect/dist/ 
    dest: /var/www/collect/html

- name: Set permissions
  file:
    dest: /var/www/collect/html
    owner: root
    group: root
    mode: 0755
    recurse: yes

